### ISSUE TITLE
no-console

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#16]
Disallow Use of console
http://eslint.org/docs/rules/no-console

**Comment by gregersrygg** [comment]
Eh, `console.log` is the recommended way to print to the console in node. So maybe we only should have this rule for the browser? It can be annoying when working with many node-scripts, like CLI-tools, and I don't like to have exceptions from the rules all over the place...

So, vote here to turn it off for node.

**Comment by SimenB** [comment]
See #49
