### ISSUE TITLE
block-spacing

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#20]
Disallow or enforce spaces inside of single line blocks.
http://eslint.org/docs/rules/block-spacing

**Comment by SimenB** [comment]
Do we allow single line functions? If we do, 👍 from me. Otherwise it should be disabled

**Comment by gregersrygg** [comment]
Eh, no, at the moment we don't allow the opening and closing of a block at the same line. Which is crazy in my view... Will create a separate issue with `"allowSingleLine": true` for [brace-style](http://eslint.org/docs/rules/brace-style).
