### ISSUE TITLE
max-depth

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#23]
Limit Maximum Depth
http://eslint.org/docs/rules/max-depth

**Comment by SimenB** [comment]
+0

If added, should be same as (or just replace) `max-nested-callbacks`

**Comment by gregersrygg** [comment]
`max-depth` seems to only apply to within current function (and not inner functions), so it actually helps us avoid many levels of indentation without getting in the way like `max-nested-callback` does.

**Comment by SimenB** [comment]
Then it's 👍  from me!
