### ISSUE TITLE
max-len

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#24]
Limit Maximum Length of Line
http://eslint.org/docs/rules/max-len
options: 140
options: 4
options: ignoreComments = true
options: ignoreUrls = true

**Comment by SimenB** [comment]
I don't really care, but it should be 140 if added 😄 We all use widescreens

**Comment by gregersrygg** [comment]
We could have even longer lines for all I care, but I'm afraid we might get some code that is wrapped at 80/100/120 if we don't say anything.

**Comment by peternic** [comment]
Do not like more than 140, even though we use widescreens ;-), better to position multiple files horizontal.

**Comment by SimenB** [comment]
I suggest `"max-len": ["error", 140, { "ignoreTrailingComments": true, "ignoreUrls": true }]`

`tabWidth` is automatically set to 4, which is both correct and ignored, as we use spaces, no need to mess with it.
