### ISSUE TITLE
max-params

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#25]
Limit Maximum Number of Parameters
http://eslint.org/docs/rules/max-params
options: 5

**Comment by SimenB** [comment]
Why is this needed?

**Comment by gregersrygg** [comment]
I find it hard to position arguments when a function has that many arguments. Especially when many of them are optional.
Objects are easier to read when many args in my opinion, and with destructuring it's super-sweet imo...

// bad
someFunc(null, null, null, true);

// good
someFunc({ isAwesome: true });

**Comment by SimenB** [comment]
Ah yes, good point. At least with destructuring it makes sense 😄
