### ISSUE TITLE
max-statements

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#26]
Limit Maximum Number of Statements
http://eslint.org/docs/rules/max-statements
options: 20

**Comment by SimenB** [comment]
I don't see the value here

**Comment by gregersrygg** [comment]
When I think about it, this can cause trouble when doing dependency injection with a function wrapping around all inner functions. As well as for unit-tests with long describe functions. So we should probably set it to off.

**Comment by SimenB** [comment]
3 nos means it can't get majority vote
