### ISSUE TITLE
brace-style

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#29]
Allow start and end of a block on the same line.
http://eslint.org/docs/rules/brace-style

This will allow this kind of code:

```js
function nop() { return; }

if (foo) { bar(); }

if (foo) { bar(); }
else { baz(); }

try { somethingRisky(); }
catch(e) { handleError(); }
```

If not we have to make them multiline:

```js
function nop() {
    return;
}

if (foo) {
    bar();
}

if (foo) {
    bar();
}
else {
    baz();
}

try {
    somethingRisky();
} catch(e) {
    handleError();
}
```

**Comment by SimenB** [comment]
No opinion on this, but I IntelliJ auto format adds the line breaks by default (can be changed, but it's still annoying). Same with `object-curly-spaces`, so no real issue, I suppose 😄
