### ISSUE TITLE
prefer-arrow-callback

### ISSUE THREAD

**Issue by SimenB** [finn-no/eslint-config-finn#36]
This is more concise, and fixes the "problem" (confusion?) WRT `this`.

http://eslint.org/docs/rules/prefer-arrow-callback

Might be annoying to implement, but still.

**Comment by gregersrygg** [comment]
Arrow functions are something different than a plain function, so I think it's wrong to enforce it. In most cases you should not rely on `this` in a callback.
Also on Node 4.x you don't have rest arguments, so then you might need to use `arguments`, which is not available when using arrow functions.

**Comment by SimenB** [comment]
It doesn't flag errors if you already use `this` or `arguments`

**Comment by sveisvei** [comment]
@gregersrygg  :) Node 4 is soon gone internally maybe? Not many arguments to stay at 4 imo. (even thought its LTS)

**Comment by SimenB** [comment]
6 will be LTS this fall sometime

**Comment by gregersrygg** [comment]
I'm not sure it's a good idea to enforce the use of arrow-functions. Regular functions can have a name - arrow functions not.

I'm +0 if we can enable `allowNamedFunctions`.
