### ISSUE TITLE
prefer-rest-params

### ISSUE THREAD

**Issue by SimenB** [finn-no/eslint-config-finn#39]
Avoids the `arguments` object.

http://eslint.org/docs/rules/prefer-rest-params

**Comment by gregersrygg** [comment]
Too early. Node 4.x (and maybe 5.x) does not support rest params.

**Comment by SimenB** [comment]
Requires transpilation, yeah...

**Comment by gregersrygg** [comment]
The transpilation can have a performance-impact on Node.js, and code execution performance is more important server-side than client-side. So my opinion is that transpilation should be avoided for Node.js, and thus we should not have rules enforcing transpilation.

**Comment by SimenB** [comment]
What about this: in `finn/node4` this rule is turned off, but it's on by default.
