### ISSUE TITLE
template-curly-spacing

### ISSUE THREAD

**Issue by SimenB** [finn-no/eslint-config-finn#46]
http://eslint.org/docs/rules/template-curly-spacing

**Comment by sveisvei** [comment]
I say `never`.

**Comment by SimenB** [comment]
Vote for `never` ^, and `always` here 😀

**Comment by gregersrygg** [comment]
We have spaces for all other curlies, and it can be quite cluttered with expressions close to the curly-braces imo... So my vote goes for `always`.

**Comment by peternic** [comment]
I say **never**, think it is more readable when compact in template strings.

**Comment by SimenB** [comment]
Aye. Spaced for key value pairs, but single things (like array values or template strings) are fine without space
