### ISSUE TITLE
Stats script all our repos

### ISSUE THREAD

**Issue by sveisvei** [finn-no/eslint-config-finn#5]
https://www.npmjs.com/package/eslint-stats 
We should create a script that can run on all our repos (ref @SimenB)

**Comment by SimenB** [comment]
I can do that

**Comment by SimenB** [comment]
Current WIP

![image](https://cloud.githubusercontent.com/assets/1404810/16040827/638b2dc4-3232-11e6-833d-81b975c723e9.png)

**Comment by sveisvei** [comment]
@SimenB think we can close this one, spinned off into own project.
