### ISSUE TITLE
Turn off `max-nested-callbacks`

### ISSUE THREAD

**Issue by SimenB** [finn-no/eslint-config-finn#57]
*Description updated by Gregers:*
When writing tests you often have many nested callbacks for `describe` and `it`, so you can hardly have any callbacks in your tests before this rule starts to complain.

It is possible to have a .eslintrc file in the tests folder, but some prefer to have the tests and source files side by side.

http://eslint.org/docs/rules/max-nested-callbacks

**Comment by peternic** [comment]
I think this is good in production code, but a nightmare in tests.

In travel-app, I have now added a .eslintrc for the test folders turning the rule off.

Remembers someone said that in jest (maybe i remember wrong), tests and source lives side by side, and thus it is difficult to add .eslintrc to the tests...

**Comment by SimenB** [comment]
Yup, that's right.

**Comment by gregersrygg** [comment]
In my opinion it should not be necessary to turn off rules for tests. We should have reasonable defaults. I would like to avoid too many nested callbacks, but unfortunately the implementation of this rule is worthless.

**Comment by kmkr** [comment]
What about increasing to max 5?

**Comment by SimenB** [comment]
@kmkr WFM, could you provide a PR?
