### ISSUE TITLE
Turn off no-else-return

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/eslint-config-finn#60]
@runeh suggested to turn off `no-else-return` because the `else` *reads* better than not having it. According to the rule docs, it exists because:

> If an if block contains a return statement, the else block becomes unnecessary

Which is the minifiers job.

I agree with Rune that this rule is only in the way, and does not make the code more readable. Probably makes it harder to read in some cases.

**Comment by CMTegner** [comment]
Having explicit `else` not only makes code easier to grok, but it also helps prevent errors like this:

```js
if (condition) {
  annotate(value) // <- forget to return annotated value
}
return value // similar enough to annotatedValue to not get noticed during testing
```

**Comment by SimenB** [comment]
I don't really care, so I suppose I'm 👍  on removing it 😄
