### ISSUE TITLE
Error on import and export

### ISSUE THREAD

**Issue by torarnek** [finn-no/eslint-config-finn#67]
I get the following error when using import/export syntax:

`error  Parsing error: 'import' and 'export' may appear only with 'sourceType: module'`

I had to add the following to my own .eslintrc:

`  "parserOptions": {
    "sourceType": "module"
  }
`

**Comment by sveisvei** [comment]
That is correct. If you are using es6 modules, use [es-modules](https://github.com/finn-no/eslint-config-finn/blob/master/packages/eslint-config-finn/es-modules.js) that extends [spt env-es6-module](https://github.com/schibsted/eslint-config-spt/blob/master/env-es6-modules.js)
