### ISSUE TITLE
Add `no-multi-spaces` rule

### ISSUE THREAD

**Issue by SimenB** [finn-no/eslint-config-finn#73]
http://eslint.org/docs/rules/no-multi-spaces

Set to off in spt config

/cc @sveisvei @peternic @CMTegner

**Comment by peternic** [comment]
Think it is good to get rid of spaces, but not sure what or if exceptions should be allowed.

**Comment by SimenB** [comment]
The only thing I've seen is people lining up config

```js
option             : false
optionWithLongName : true
```
or

```js
option:             false
optionWithLongName: true
```

Which I personally find weird, but that is covered by http://eslint.org/docs/rules/key-spacing
